In [2]:
import newspaper
import json
import pandas as pd

#read JSON file
with open('uk_news_outlets.json','r') as myfile:
    data = myfile.read()

#Parse file

obj=json.loads(data)
table_articles = pd.DataFrame(columns=["Article","Source Url","Url","Authors","Title","Publish_date","Text"])
num_art = 0

#Add a while to know which ones 
#Read the urls and get the articles
for i in range(1):
    for link in (obj['news_outlets']):
        print(link)
        web_page = newspaper.build(link['url'])
        for article in web_page.articles:  
            dict_art={}
            article.download()
            article.parse()
            dict_art =pd.DataFrame({ "Article": "Article {}".format(num_art),
                                     "Source Url" : article.source_url,
                                     "Url" : article.url,
                                     "Authors": article.authors,
                                     "Title": article.title,
                                     "Publish_date": article.publish_date,
                                     "Text": article.text})
            table_articles= pd.concat([table_articles,dict_art],axis=0)   
            num_art+=1


art_csv = table_articles.to_csv('art_data1.csv')

{'name': 'BBC', 'url': 'https://www.bbc.co.uk/'}
{'name': 'The Guardian', 'url': 'https://www.theguardian.com/uk'}
{'name': 'The Telegraph', 'url': 'https://www.telegraph.co.uk/'}
{'name': 'The Independent', 'url': 'https://www.independent.co.uk/'}
{'name': 'Channel 4', 'url': 'https://www.channel4.com/'}
{'name': 'Huffington Post', 'url': 'https://www.huffingtonpost.co.uk/'}
{'name': 'Evening Standard', 'url': 'https://www.standard.co.uk'}
{'name': 'Wired', 'url': 'https://www.wired.co.uk/'}
{'name': 'Daily Record', 'url': 'https://www.dailyrecord.co.uk/'}
{'name': 'Wales Online', 'url': 'https://www.walesonline.co.uk'}
{'name': 'Sky', 'url': 'https://www.sky.com/'}
{'name': 'Metro', 'url': 'https://metro.co.uk/'}

In [3]:
table_articles.head()

,Article,Source Url,Url,Authors,Title,Publish_date,Text
0,Article 1,https://www.theguardian.com/uk,https://www.theguardian.com/business/2019/aug/...,Larry Elliott,UK economy contracts on back of Brexit uncerta...,2019-08-09 00:00:00,Gross domestic product (GDP) measures the tota...
0,Article 2,https://www.theguardian.com/uk,https://www.theguardian.com/business/live/2019...,Jasper Jolly,Recession fears rise after UK economy contract...,2019-08-09 00:00:00,What term do you want to search? Search with g...
0,Article 4,https://www.theguardian.com/uk,https://www.theguardian.com/global-development...,Gethin Chamberlain,Schoolchildren in China work overnight to prod...,2019-08-08 00:00:00,Hundreds of schoolchildren have been drafted i...
0,Article 5,https://www.theguardian.com/uk,https://www.theguardian.com/uk-news/2019/aug/0...,Pa Media,Roof with a view: Helter skelter installed in ...,2019-08-09 00:00:00,Ceiling ‘every bit as wonderful’ as the Sistin...
0,Article 6,https://www.theguardian.com/uk,https://www.theguardian.com/us-news/2019/aug/0...,Julia Carrie Wong,Trump campaign’s Facebook ads target Latinos i...,2019-08-08 00:00:00,"On Monday, less than 48 hours after 22 people ..."